Repository is-project-4th-year/team-profile-site-push-request-pirates, pull requests merged in 2025-06, with the labels that each got.

#8 task: Add Portfolio section for Noel
  index.html
Labels: good first issue

#10 2 add portfolio section for brian kyalo
  Bull.png
  index.html
Labels: Team Profile

#15 docs: add documentation section for Brian Kyalo
  documentation.md
Labels: documentation
